/**
 * `gum <command> --help`, in the layout of upstream's kong help.
 * The data in help-data.ts is generated by scripts/gen-help.ts.
 */
import { COMMAND_HELP, STYLE_FLAGS } from './help-data.js';

export interface FlagHelp {
  name: string;
  short?: string;
  value?: string;
  help: string;
  default?: string;
  env?: string;
  negatable?: boolean;
  enum?: string;
}

export interface StyleFlagHelp {
  name: string;
  value?: string;
  help: string;
  default?: string;
  enum?: string;
}

export interface CommandHelp {
  summary: string;
  args: { name: string; help: string }[];
  flags: FlagHelp[];
  /** Style flag prefixes ("cursor."), or "" for the unprefixed style flags. */
  styles: string[];
}

function flagLabel(f: { name: string; short?: string; value?: string; negatable?: boolean; default?: string }): string {
  const short = f.short ? `-${f.short}, ` : '    ';
  const name = f.negatable ? `--[no-]${f.name}` : `--${f.name}`;
  // Defaults are shown as kong does: quoted when they contain a space.
  const shown = f.default && /\s/.test(f.default) ? `"${f.default}"` : f.default;
  const value = f.value ? `=${shown || f.value}` : '';
  return `  ${short}${name}${value}`;
}

function flagText(f: { help: string; env?: string; enum?: string }): string {
  let text = f.help;
  if (f.enum && !text.includes(f.enum)) text += ` (${f.enum})`;
  if (f.env) text += ` ($${f.env})`;
  return text;
}

function table(rows: [string, string][]): string[] {
  const width = Math.max(...rows.map(([l]) => l.length)) + 4;
  return rows.map(([l, t]) => (t ? l.padEnd(width) + t : l));
}

/** Help for one command, or undefined if gum has no such command. */
export function commandHelp(command: string): string | undefined {
  const help = COMMAND_HELP[command];
  if (!help) return undefined;

  const usageArgs = help.args.map((a) => ` ${a.name}`).join('');
  const lines = [`Usage: gum ${command}${usageArgs} [flags]`, '', help.summary, ''];

  if (help.args.length > 0) {
    lines.push('Arguments:', ...table(help.args.map((a) => [`  ${a.name}`, a.help])), '');
  }

  const rows: [string, string][] = [
    ['  -h, --help', 'Show context-sensitive help.'],
    ...help.flags.map((f): [string, string] => [flagLabel(f), flagText(f)]),
  ];
  lines.push('Flags:', ...table(rows));

  if (help.styles.includes('')) {
    lines.push('', 'Style Flags:', ...table(STYLE_FLAGS.map((f): [string, string] => [flagLabel(f), flagText(f)])));
  }
  const prefixes = help.styles.filter((p) => p !== '');
  if (prefixes.length > 0) {
    const keys = STYLE_FLAGS.map((f) => f.name).join(', ');
    lines.push(
      '',
      'Style Flags:',
      ...prefixes.map((p) => `  --${p}<key>`),
      '',
      `  where <key> is one of: ${keys}`,
      '  (see gum style --help)',
    );
  }
  return lines.join('\n') + '\n';
}
