// Generated by scripts/gen-help.ts from gum v0.17.0; do not edit.
import type { CommandHelp, StyleFlagHelp } from './help.js';

export const STYLE_FLAGS: StyleFlagHelp[] = [
  {
    "name": "foreground",
    "value": "STRING",
    "help": "Foreground Color"
  },
  {
    "name": "background",
    "value": "STRING",
    "help": "Background Color"
  },
  {
    "name": "border",
    "value": "STRING",
    "help": "Border Style",
    "default": "none",
    "enum": "none,hidden,normal,rounded,thick,double"
  },
  {
    "name": "border-background",
    "value": "STRING",
    "help": "Border Background Color"
  },
  {
    "name": "border-foreground",
    "value": "STRING",
    "help": "Border Foreground Color"
  },
  {
    "name": "align",
    "value": "STRING",
    "help": "Text Alignment",
    "default": "left",
    "enum": "left,center,right,bottom,middle,top"
  },
  {
    "name": "height",
    "value": "INT",
    "help": "Text height",
    "default": "0"
  },
  {
    "name": "width",
    "value": "INT",
    "help": "Text width",
    "default": "0"
  },
  {
    "name": "margin",
    "value": "STRING",
    "help": "Text margin",
    "default": "0 0"
  },
  {
    "name": "padding",
    "value": "STRING",
    "help": "Text padding",
    "default": "0 0"
  },
  {
    "name": "bold",
    "help": "Bold text",
    "default": "false"
  },
  {
    "name": "faint",
    "help": "Faint text",
    "default": "false"
  },
  {
    "name": "italic",
    "help": "Italicize text",
    "default": "false"
  },
  {
    "name": "strikethrough",
    "help": "Strikethrough text",
    "default": "false"
  },
  {
    "name": "underline",
    "help": "Underline text",
    "default": "false"
  }
];

export const COMMAND_HELP: Record<string, CommandHelp> = {
  "choose": {
    "summary": "Choose an option from a list of choices",
    "args": [
      {
        "name": "[<options> ...]",
        "help": "Options to choose from."
      }
    ],
    "flags": [
      {
        "name": "limit",
        "value": "INT",
        "help": "Maximum number of options to pick",
        "default": "1"
      },
      {
        "name": "no-limit",
        "help": "Pick unlimited number of options (ignores limit)",
        "default": "false"
      },
      {
        "name": "ordered",
        "help": "Maintain the order of the selected options",
        "default": "false"
      },
      {
        "name": "height",
        "value": "INT",
        "help": "Height of the list",
        "default": "10"
      },
      {
        "name": "cursor",
        "value": "STRING",
        "help": "Prefix to show on item that corresponds to the cursor position",
        "default": "> "
      },
      {
        "name": "show-help",
        "help": "Show help keybinds",
        "default": "true",
        "negatable": true
      },
      {
        "name": "timeout",
        "value": "DURATION",
        "help": "Timeout until choose returns selected element",
        "default": "0s"
      },
      {
        "name": "header",
        "value": "STRING",
        "help": "Header value",
        "default": "Choose:"
      },
      {
        "name": "cursor-prefix",
        "value": "STRING",
        "help": "Prefix to show on the cursor item (hidden if limit is 1)",
        "default": "• "
      },
      {
        "name": "selected-prefix",
        "value": "STRING",
        "help": "Prefix to show on selected items (hidden if limit is 1)",
        "default": "✓ "
      },
      {
        "name": "unselected-prefix",
        "value": "STRING",
        "help": "Prefix to show on unselected items (hidden if limit is 1)",
        "default": "• "
      },
      {
        "name": "selected",
        "value": "STRING,...",
        "help": "Options that should start as selected (selects all if given *)",
        "default": ""
      },
      {
        "name": "select-if-one",
        "help": "Select the given option if there is only one",
        "default": "false"
      },
      {
        "name": "input-delimiter",
        "value": "STRING",
        "help": "Option delimiter when reading from STDIN",
        "default": "\\n"
      },
      {
        "name": "output-delimiter",
        "value": "STRING",
        "help": "Option delimiter when writing to STDOUT",
        "default": "\\n"
      },
      {
        "name": "label-delimiter",
        "value": "STRING",
        "help": "Allows to set a delimiter, so options can be set as label:value",
        "default": ""
      },
      {
        "name": "strip-ansi",
        "help": "Strip ANSI sequences when reading from STDIN",
        "default": "true",
        "negatable": true
      },
      {
        "name": "padding",
        "value": "STRING",
        "help": "Padding",
        "default": "0 0"
      }
    ],
    "styles": [
      "cursor.",
      "header.",
      "selected."
    ]
  },
  "confirm": {
    "summary": "Ask a user to confirm an action",
    "args": [
      {
        "name": "<prompt>",
        "help": "Prompt to display."
      }
    ],
    "flags": [
      {
        "name": "default",
        "help": "Default confirmation action",
        "default": "true"
      },
      {
        "name": "show-output",
        "help": "Print prompt and chosen action to output",
        "default": "false"
      },
      {
        "name": "affirmative",
        "value": "STRING",
        "help": "The title of the affirmative action",
        "default": "Yes"
      },
      {
        "name": "negative",
        "value": "STRING",
        "help": "The title of the negative action",
        "default": "No"
      },
      {
        "name": "show-help",
        "help": "Show help key binds",
        "default": "true",
        "negatable": true
      },
      {
        "name": "timeout",
        "value": "DURATION",
        "help": "Timeout until confirm returns selected value or default if provided",
        "default": "0s"
      },
      {
        "name": "padding",
        "value": "STRING",
        "help": "Padding",
        "default": "0 0"
      }
    ],
    "styles": [
      "prompt.",
      "selected.",
      "unselected."
    ]
  },
  "file": {
    "summary": "Pick a file from a folder",
    "args": [
      {
        "name": "[<path>]",
        "help": "The path to the folder to begin traversing"
      }
    ],
    "flags": [
      {
        "name": "cursor",
        "short": "c",
        "value": "STRING",
        "help": "The cursor character",
        "default": ">"
      },
      {
        "name": "all",
        "short": "a",
        "help": "Show hidden and 'dot' files",
        "default": "false"
      },
      {
        "name": "permissions",
        "short": "p",
        "help": "Show file permissions",
        "default": "true",
        "negatable": true
      },
      {
        "name": "size",
        "short": "s",
        "help": "Show file size",
        "default": "true",
        "negatable": true
      },
      {
        "name": "file",
        "help": "Allow files selection",
        "default": "true"
      },
      {
        "name": "directory",
        "help": "Allow directories selection",
        "default": "false"
      },
      {
        "name": "show-help",
        "help": "Show help key binds",
        "default": "true",
        "negatable": true
      },
      {
        "name": "timeout",
        "value": "DURATION",
        "help": "Timeout until command aborts without a selection",
        "default": "0s"
      },
      {
        "name": "header",
        "value": "STRING",
        "help": "Header value",
        "default": ""
      },
      {
        "name": "height",
        "value": "INT",
        "help": "Maximum number of files to display",
        "default": "10"
      },
      {
        "name": "padding",
        "value": "STRING",
        "help": "Padding",
        "default": "0 0"
      }
    ],
    "styles": [
      "cursor.",
      "symlink.",
      "directory.",
      "file.",
      "permissions.",
      "selected.",
      "file-size.",
      "header."
    ]
  },
  "format": {
    "summary": "Format a string using a template",
    "args": [
      {
        "name": "[<template> ...]",
        "help": "Template string to format (can also be provided via stdin)"
      }
    ],
    "flags": [
      {
        "name": "theme",
        "value": "STRING",
        "help": "Glamour theme to use for markdown formatting",
        "default": "pink"
      },
      {
        "name": "language",
        "short": "l",
        "value": "STRING",
        "help": "Programming language to parse code",
        "default": ""
      },
      {
        "name": "strip-ansi",
        "help": "Strip ANSI sequences when reading from STDIN",
        "default": "true",
        "negatable": true
      },
      {
        "name": "type",
        "short": "t",
        "value": "STRING",
        "help": "Format to use (markdown,template,code,emoji)",
        "default": "markdown",
        "enum": "markdown,template,code,emoji"
      }
    ],
    "styles": []
  },
  "input": {
    "summary": "Prompt for some input",
    "args": [],
    "flags": [
      {
        "name": "placeholder",
        "value": "STRING",
        "help": "Placeholder value",
        "default": "Type something...",
        "env": "GUM_INPUT_PLACEHOLDER"
      },
      {
        "name": "prompt",
        "value": "STRING",
        "help": "Prompt to display",
        "default": "> ",
        "env": "GUM_INPUT_PROMPT"
      },
      {
        "name": "cursor.mode",
        "value": "STRING",
        "help": "Cursor mode",
        "default": "blink",
        "enum": "blink,hide,static"
      },
      {
        "name": "value",
        "value": "STRING",
        "help": "Initial value (can also be passed via stdin)",
        "default": ""
      },
      {
        "name": "char-limit",
        "value": "INT",
        "help": "Maximum value length (0 for no limit)",
        "default": "400"
      },
      {
        "name": "width",
        "value": "INT",
        "help": "Input width (0 for terminal width)",
        "default": "0"
      },
      {
        "name": "password",
        "help": "Mask input characters",
        "default": "false"
      },
      {
        "name": "show-help",
        "help": "Show help keybinds",
        "default": "true",
        "negatable": true
      },
      {
        "name": "header",
        "value": "STRING",
        "help": "Header value",
        "default": ""
      },
      {
        "name": "timeout",
        "value": "DURATION",
        "help": "Timeout until input aborts",
        "default": "0s"
      },
      {
        "name": "strip-ansi",
        "help": "Strip ANSI sequences when reading from STDIN",
        "default": "true",
        "negatable": true
      },
      {
        "name": "padding",
        "value": "STRING",
        "help": "Padding",
        "default": "0 0"
      }
    ],
    "styles": [
      "prompt.",
      "placeholder.",
      "cursor.",
      "header."
    ]
  },
  "join": {
    "summary": "Join text vertically or horizontally",
    "args": [
      {
        "name": "<text> ...",
        "help": "Text to join."
      }
    ],
    "flags": [
      {
        "name": "align",
        "value": "STRING",
        "help": "Text alignment",
        "default": "left",
        "enum": "left,center,right,bottom,middle,top"
      },
      {
        "name": "vertical",
        "help": "Join (potentially multi-line) strings vertically",
        "default": "false"
      }
    ],
    "styles": []
  },
  "log": {
    "summary": "Log messages to output",
    "args": [
      {
        "name": "<text> ...",
        "help": "Text to log"
      }
    ],
    "flags": [
      {
        "name": "file",
        "short": "o",
        "value": "STRING",
        "help": "Log to file",
        "default": ""
      },
      {
        "name": "format",
        "short": "f",
        "help": "Format message using printf",
        "default": "false"
      },
      {
        "name": "formatter",
        "value": "STRING",
        "help": "The log formatter to use",
        "default": "text",
        "enum": "json,logfmt,text"
      },
      {
        "name": "level",
        "short": "l",
        "value": "STRING",
        "help": "The log level to use",
        "default": "none",
        "enum": "none,debug,info,warn,error,fatal"
      },
      {
        "name": "prefix",
        "value": "STRING",
        "help": "Prefix to print before the message",
        "default": ""
      },
      {
        "name": "structured",
        "short": "s",
        "help": "Use structured logging",
        "default": "false"
      },
      {
        "name": "time",
        "short": "t",
        "value": "STRING",
        "help": "The time format to use (kitchen, layout, ansic, rfc822, etc...)",
        "default": ""
      },
      {
        "name": "min-level",
        "value": "STRING",
        "help": "Minimal level to show",
        "default": ""
      }
    ],
    "styles": [
      "level.",
      "time.",
      "prefix.",
      "message.",
      "key.",
      "value.",
      "separator."
    ]
  },
  "pager": {
    "summary": "Scroll through a file",
    "args": [
      {
        "name": "[<content>]",
        "help": "Display content to scroll"
      }
    ],
    "flags": [
      {
        "name": "show-line-numbers",
        "help": "Show line numbers",
        "default": "true"
      },
      {
        "name": "soft-wrap",
        "help": "Soft wrap lines",
        "default": "true",
        "negatable": true
      },
      {
        "name": "timeout",
        "value": "DURATION",
        "help": "Timeout until command exits",
        "default": "0s"
      }
    ],
    "styles": [
      "line-number.",
      "match.",
      "match-highlight."
    ]
  },
  "spin": {
    "summary": "Display spinner while running a command",
    "args": [
      {
        "name": "<command> ...",
        "help": "Command to run"
      }
    ],
    "flags": [
      {
        "name": "show-output",
        "help": "Show or pipe output of command during execution (shows both STDOUT and STDERR)",
        "default": "false"
      },
      {
        "name": "show-error",
        "help": "Show output of command only if the command fails",
        "default": "false"
      },
      {
        "name": "show-stdout",
        "help": "Show STDOUT output",
        "default": "false"
      },
      {
        "name": "show-stderr",
        "help": "Show STDERR errput",
        "default": "false"
      },
      {
        "name": "spinner",
        "short": "s",
        "value": "STRING",
        "help": "Spinner type",
        "default": "dot",
        "enum": "line,dot,minidot,jump,pulse,points,globe,moon,monkey,meter,hamburger"
      },
      {
        "name": "title",
        "value": "STRING",
        "help": "Text to display to user while spinning",
        "default": "Loading..."
      },
      {
        "name": "align",
        "short": "a",
        "value": "STRING",
        "help": "Alignment of spinner with regard to the title",
        "default": "left",
        "enum": "left,right"
      },
      {
        "name": "timeout",
        "value": "DURATION",
        "help": "Timeout until spin command aborts",
        "default": "0s"
      }
    ],
    "styles": [
      "spinner.",
      "title."
    ]
  },
  "style": {
    "summary": "Apply coloring, borders, spacing to text",
    "args": [
      {
        "name": "[<text> ...]",
        "help": "Text to which to apply the style"
      }
    ],
    "flags": [
      {
        "name": "trim",
        "help": "Trim whitespaces on every input line",
        "default": "false"
      },
      {
        "name": "strip-ansi",
        "help": "Strip ANSI sequences when reading from STDIN",
        "default": "true",
        "negatable": true
      }
    ],
    "styles": [
      ""
    ]
  },
  "table": {
    "summary": "Render a table of data",
    "args": [],
    "flags": [
      {
        "name": "separator",
        "short": "s",
        "value": "STRING",
        "help": "Row separator",
        "default": ","
      },
      {
        "name": "columns",
        "short": "c",
        "value": "STRING,...",
        "help": "Column names",
        "default": ""
      },
      {
        "name": "widths",
        "short": "w",
        "value": "STRING,...",
        "help": "Column widths",
        "default": ""
      },
      {
        "name": "height",
        "value": "INT",
        "help": "Table height",
        "default": "0"
      },
      {
        "name": "print",
        "short": "p",
        "help": "static print",
        "default": "false"
      },
      {
        "name": "file",
        "short": "f",
        "value": "STRING",
        "help": "file path",
        "default": ""
      },
      {
        "name": "border",
        "short": "b",
        "value": "STRING",
        "help": "border style",
        "default": "rounded",
        "enum": "rounded,thick,normal,hidden,double,none"
      },
      {
        "name": "show-help",
        "help": "Show help keybinds",
        "default": "true",
        "negatable": true
      },
      {
        "name": "hide-count",
        "help": "Hide item count on help keybinds",
        "default": "false",
        "negatable": true
      },
      {
        "name": "return-column",
        "short": "r",
        "value": "INT",
        "help": "Which column number should be returned instead of whole row as string. Default=0 returns whole Row",
        "default": "0"
      },
      {
        "name": "timeout",
        "value": "DURATION",
        "help": "Timeout until choose returns selected element",
        "default": "0s"
      },
      {
        "name": "padding",
        "value": "STRING",
        "help": "Padding",
        "default": "0 0"
      }
    ],
    "styles": [
      "border.",
      "cell.",
      "header.",
      "selected."
    ]
  },
  "write": {
    "summary": "Prompt for long-form text",
    "args": [],
    "flags": [
      {
        "name": "width",
        "value": "INT",
        "help": "Text area width (0 for terminal width)",
        "default": "0"
      },
      {
        "name": "height",
        "value": "INT",
        "help": "Text area height",
        "default": "5"
      },
      {
        "name": "header",
        "value": "STRING",
        "help": "Header value",
        "default": ""
      },
      {
        "name": "placeholder",
        "value": "STRING",
        "help": "Placeholder value",
        "default": "Write something...",
        "env": "GUM_WRITE_PLACEHOLDER"
      },
      {
        "name": "prompt",
        "value": "STRING",
        "help": "Prompt to display",
        "default": "┃ "
      },
      {
        "name": "show-line-numbers",
        "help": "Show line numbers",
        "default": "false"
      },
      {
        "name": "value",
        "value": "STRING",
        "help": "Initial value (can be passed via stdin)",
        "default": ""
      },
      {
        "name": "char-limit",
        "value": "INT",
        "help": "Maximum value length (0 for no limit)",
        "default": "0"
      },
      {
        "name": "max-lines",
        "value": "INT",
        "help": "Maximum number of lines (0 for no limit)",
        "default": "0"
      },
      {
        "name": "show-help",
        "help": "Show help key binds",
        "default": "true",
        "negatable": true
      },
      {
        "name": "cursor.mode",
        "value": "STRING",
        "help": "Cursor mode",
        "default": "blink",
        "enum": "blink,hide,static"
      },
      {
        "name": "timeout",
        "value": "DURATION",
        "help": "Timeout until choose returns selected element",
        "default": "0s"
      },
      {
        "name": "strip-ansi",
        "help": "Strip ANSI sequences when reading from STDIN",
        "default": "true",
        "negatable": true
      },
      {
        "name": "padding",
        "value": "STRING",
        "help": "Padding",
        "default": "0 0"
      }
    ],
    "styles": [
      "base.",
      "cursor-line-number.",
      "cursor-line.",
      "cursor.",
      "end-of-buffer.",
      "line-number.",
      "header.",
      "placeholder.",
      "prompt."
    ]
  }
};
